"""Constants for the OutBack MATE3s integration."""

from datetime import timedelta

DOMAIN = "outback_mate3s"

CONF_HOST = "host"
CONF_PORT = "port"
CONF_UNIT_ID = "unit_id"
CONF_WRITE_PASSWORD = "write_password"

DEFAULT_PORT = 502
DEFAULT_UNIT_ID = 1
DEFAULT_WRITE_PASSWORD = "1732"
DEFAULT_SCAN_INTERVAL = timedelta(seconds=10)
CONTROL_SCAN_INTERVAL = timedelta(minutes=5)

SUNSPEC_BASE = 40000
SUNSPEC_SIGNATURE = (0x5375, 0x6E53)
SUNSPEC_END_DID = 65535

DID_OUTBACK_GATEWAY = 64110
DID_CHARGE_CONTROLLER_REALTIME = 64111
DID_CHARGE_CONTROLLER_CONFIG = 64112
DID_RADIAN_SPLIT_REALTIME = 64115
DID_FNDC_REALTIME = 64118
DID_OUTBACK_SYSTEM_CONTROL = 64120

